### ISSUE TITLE
Cookie Domain Rewriting?

### ISSUE THREAD

**Issue by StevenACoffman** [bkielbasa/go-proxy#1]
Is there a way to rewrite the domain of `set-cookie` headers?

**Comment by bkielbasa** [comment]
yeah, of course. Please notice that you have access to the request which will be sent to the proxied server https://github.com/bkielbasa/go-proxy/blob/master/main.go#L41. You can do what you want there :)

**Comment by bkielbasa** [comment]
I assume that I answered your question :)
